-- =============================================================================
-- FICHIER  : pau/02b_grants.sql
-- EXECUTÉ  : par APPLI_GLPI (propriétaire des tables Pau)
-- NOTION   : GRANTs sur objets côté Pau
-- =============================================================================

-- Droits du technicien Pau
-- Il peut gérer les équipements et consulter les référentiels utiles
GRANT SELECT, INSERT, UPDATE ON CYT_COMPUTERS        TO ROLE_TECH_PAU;
GRANT SELECT, INSERT, UPDATE ON CYT_COMPUTERS_DETAIL TO ROLE_TECH_PAU;
GRANT SELECT, INSERT, UPDATE ON CYT_LOCATIONS        TO ROLE_TECH_PAU;
GRANT SELECT, INSERT, UPDATE ON CYT_NETWORKPORTS     TO ROLE_TECH_PAU;
GRANT SELECT, INSERT, UPDATE ON CYT_NETEQUIP         TO ROLE_TECH_PAU;
GRANT SELECT, INSERT, UPDATE ON CYT_IPADDRESSES      TO ROLE_TECH_PAU;
GRANT SELECT                 ON CYT_ENTITIES         TO ROLE_TECH_PAU;
GRANT SELECT                 ON CYT_MANUFACTURERS    TO ROLE_TECH_PAU;
GRANT SELECT                 ON CYT_NETWORKS         TO ROLE_TECH_PAU;
GRANT SELECT                 ON CYT_USERS            TO ROLE_TECH_PAU;

-- Droits de l'auditeur Pau
-- Lecture seule pour consulter les données et les logs
GRANT SELECT ON CYT_COMPUTERS    TO ROLE_AUDITEUR_PAU;
GRANT SELECT ON CYT_USERS        TO ROLE_AUDITEUR_PAU;
GRANT SELECT ON CYT_AUDIT_LOG    TO ROLE_AUDITEUR_PAU;
GRANT SELECT ON CYT_NETWORKPORTS TO ROLE_AUDITEUR_PAU;
GRANT SELECT ON CYT_NETEQUIP     TO ROLE_AUDITEUR_PAU;
GRANT SELECT ON CYT_ENTITIES     TO ROLE_AUDITEUR_PAU;
GRANT SELECT ON CYT_LOCATIONS    TO ROLE_AUDITEUR_PAU;
GRANT SELECT ON CYT_IPADDRESSES  TO ROLE_AUDITEUR_PAU;

-- Droits directs pour AUDITEUR_PAU
-- Obligatoire pour les accès via DBLink depuis Cergy
GRANT SELECT ON CYT_COMPUTERS        TO AUDITEUR_PAU;
GRANT SELECT ON CYT_COMPUTERS_DETAIL TO AUDITEUR_PAU;
GRANT SELECT ON CYT_USERS            TO AUDITEUR_PAU;
GRANT SELECT ON CYT_USERS_DETAIL     TO AUDITEUR_PAU;
GRANT SELECT ON CYT_AUDIT_LOG        TO AUDITEUR_PAU;
GRANT SELECT ON CYT_NETWORKPORTS     TO AUDITEUR_PAU;
GRANT SELECT ON CYT_NETEQUIP         TO AUDITEUR_PAU;
GRANT SELECT ON CYT_ENTITIES         TO AUDITEUR_PAU;
GRANT SELECT ON CYT_LOCATIONS        TO AUDITEUR_PAU;
GRANT SELECT ON CYT_IPADDRESSES      TO AUDITEUR_PAU;
GRANT SELECT ON CYT_NETWORKS         TO AUDITEUR_PAU;

-- Vérification des privilèges
SELECT grantee, table_name, privilege
FROM   user_tab_privs_made
ORDER BY grantee, table_name, privilege;