-- =============================================================================
-- FICHIER  : cergy/02b_grants.sql
-- EXECUTÉ  : par APPLI_GLPI (propriétaire des tables)
-- NOTION   : GRANTs sur objets — le propriétaire distribue ses droits
-- ORDRE    : après 03_schema_tables.sql, 03b_fk.sql, 05_views.sql, 07_views_federated.sql
-- =============================================================================

-- ── ROLE_TECH_CERGY ──────────────────────────────────────────────────────────
GRANT SELECT, INSERT, UPDATE ON CYT_COMPUTERS        TO ROLE_TECH_CERGY;
GRANT SELECT, INSERT, UPDATE ON CYT_COMPUTERS_DETAIL TO ROLE_TECH_CERGY;
GRANT SELECT, INSERT, UPDATE ON CYT_LOCATIONS        TO ROLE_TECH_CERGY;
GRANT SELECT, INSERT, UPDATE ON CYT_NETWORKPORTS     TO ROLE_TECH_CERGY;
GRANT SELECT, INSERT, UPDATE ON CYT_PORT_LINKS       TO ROLE_TECH_CERGY;
GRANT SELECT, INSERT, UPDATE ON CYT_NETEQUIP         TO ROLE_TECH_CERGY;
GRANT SELECT, INSERT, UPDATE ON CYT_IPADDRESSES      TO ROLE_TECH_CERGY;
GRANT SELECT                 ON CYT_ENTITIES         TO ROLE_TECH_CERGY;
GRANT SELECT                 ON CYT_MANUFACTURERS    TO ROLE_TECH_CERGY;
GRANT SELECT                 ON CYT_COMPUTER_MODELS  TO ROLE_TECH_CERGY;
GRANT SELECT                 ON CYT_COMPUTER_TYPES   TO ROLE_TECH_CERGY;
GRANT SELECT                 ON CYT_NETWORKS         TO ROLE_TECH_CERGY;
GRANT SELECT                 ON CYT_USERS            TO ROLE_TECH_CERGY;
GRANT SELECT                 ON CYT_GROUPS           TO ROLE_TECH_CERGY;
GRANT SELECT                 ON CYT_GROUPS_USERS     TO ROLE_TECH_CERGY;
-- Vues accessibles au technicien
GRANT SELECT ON V_COMPUTERS_CERGY  TO ROLE_TECH_CERGY;
GRANT SELECT ON V_COMPUTERS_FULL   TO ROLE_TECH_CERGY;
GRANT SELECT ON V_NETWORK_MAPPING  TO ROLE_TECH_CERGY;

-- ── ROLE_RH ──────────────────────────────────────────────────────────────────
GRANT SELECT, INSERT, UPDATE         ON CYT_USERS          TO ROLE_RH;
GRANT SELECT, INSERT, UPDATE         ON CYT_USERS_DETAIL   TO ROLE_RH;
GRANT SELECT, INSERT, UPDATE         ON CYT_USERS_PROFILES TO ROLE_RH;
GRANT SELECT, INSERT, UPDATE, DELETE ON CYT_GROUPS_USERS   TO ROLE_RH;
GRANT SELECT                         ON CYT_PROFILES       TO ROLE_RH;
GRANT SELECT                         ON CYT_ENTITIES       TO ROLE_RH;
GRANT SELECT                         ON CYT_GROUPS         TO ROLE_RH;
-- Vues accessibles au RH
GRANT SELECT ON V_USERS_FULL         TO ROLE_RH;

-- ── ROLE_AUDITEUR ─────────────────────────────────────────────────────────────
GRANT SELECT ON CYT_COMPUTERS        TO ROLE_AUDITEUR;
GRANT SELECT ON CYT_COMPUTERS_DETAIL TO ROLE_AUDITEUR;
GRANT SELECT ON CYT_USERS            TO ROLE_AUDITEUR;
GRANT SELECT ON CYT_USERS_DETAIL     TO ROLE_AUDITEUR;
GRANT SELECT ON CYT_NETWORKPORTS     TO ROLE_AUDITEUR;
GRANT SELECT ON CYT_PORT_LINKS       TO ROLE_AUDITEUR;
GRANT SELECT ON CYT_NETEQUIP         TO ROLE_AUDITEUR;
GRANT SELECT ON CYT_NETWORKS         TO ROLE_AUDITEUR;
GRANT SELECT ON CYT_AUDIT_LOG        TO ROLE_AUDITEUR;
GRANT SELECT ON CYT_ASSET_TRANSFER   TO ROLE_AUDITEUR;
GRANT SELECT ON CYT_ENTITIES         TO ROLE_AUDITEUR;
GRANT SELECT ON CYT_LOCATIONS        TO ROLE_AUDITEUR;
GRANT SELECT ON CYT_GROUPS           TO ROLE_AUDITEUR;
GRANT SELECT ON CYT_GROUPS_USERS     TO ROLE_AUDITEUR;
GRANT SELECT ON CYT_IPADDRESSES      TO ROLE_AUDITEUR;
GRANT SELECT ON CYT_INFOCOMS         TO ROLE_AUDITEUR;
GRANT SELECT ON CYT_PROFILES         TO ROLE_AUDITEUR;
-- Vues accessibles a l auditeur
GRANT SELECT ON V_COMPUTERS_CERGY    TO ROLE_AUDITEUR;
GRANT SELECT ON V_COMPUTERS_FULL     TO ROLE_AUDITEUR;
GRANT SELECT ON V_NETWORK_MAPPING    TO ROLE_AUDITEUR;
GRANT SELECT ON V_USERS_FULL         TO ROLE_AUDITEUR;
GRANT SELECT ON V_AUDIT_RECENT       TO ROLE_AUDITEUR;
GRANT SELECT ON V_GLOBAL_COMPUTERS   TO ROLE_AUDITEUR;
GRANT SELECT ON MV_INVENTORY_GLOBAL  TO ROLE_AUDITEUR;

-- ── ROLE_DSI_ADMIN ────────────────────────────────────────────────────────────
-- DSI : vision globale Cergy + Pau via vues federees
GRANT SELECT ON V_GLOBAL_COMPUTERS   TO ROLE_DSI_ADMIN;
GRANT SELECT ON V_GLOBAL_USERS       TO ROLE_DSI_ADMIN;
GRANT SELECT ON MV_INVENTORY_GLOBAL  TO ROLE_DSI_ADMIN;
GRANT SELECT ON V_AUDIT_RECENT       TO ROLE_DSI_ADMIN;
GRANT SELECT ON V_COMPUTERS_CERGY    TO ROLE_DSI_ADMIN;
GRANT SELECT ON V_COMPUTERS_FULL     TO ROLE_DSI_ADMIN;
GRANT SELECT ON V_NETWORK_MAPPING    TO ROLE_DSI_ADMIN;
GRANT SELECT ON V_USERS_FULL         TO ROLE_DSI_ADMIN;

-- Verification
SELECT grantee, COUNT(*) AS nb_grants
FROM   user_tab_privs_made
GROUP BY grantee
ORDER BY grantee;