
WHENEVER SQLERROR CONTINUE;

ALTER TABLE CYT_LOCATIONS ADD CONSTRAINT FK_LOC_ENTITY
  FOREIGN KEY (entity_id) REFERENCES CYT_ENTITIES(entity_id);

ALTER TABLE CYT_NETWORKS ADD CONSTRAINT FK_NET_ENTITY
  FOREIGN KEY (entity_id) REFERENCES CYT_ENTITIES(entity_id);

ALTER TABLE CYT_GROUPS ADD CONSTRAINT FK_GRP_ENTITY
  FOREIGN KEY (entity_id) REFERENCES CYT_ENTITIES(entity_id);

ALTER TABLE CYT_GROUPS_USERS ADD CONSTRAINT FK_GU_USER
  FOREIGN KEY (user_id) REFERENCES CYT_USERS(user_id) ON DELETE CASCADE;

ALTER TABLE CYT_GROUPS_USERS ADD CONSTRAINT FK_GU_GROUP
  FOREIGN KEY (group_id) REFERENCES CYT_GROUPS(group_id) ON DELETE CASCADE;

ALTER TABLE CYT_NETWORKPORTS ADD CONSTRAINT FK_NETPORT_ENTITY
  FOREIGN KEY (entity_id) REFERENCES CYT_ENTITIES(entity_id);

ALTER TABLE CYT_NETWORKPORTS ADD CONSTRAINT FK_NETPORT_NETWORK
  FOREIGN KEY (network_id) REFERENCES CYT_NETWORKS(network_id);

ALTER TABLE CYT_PORT_LINKS ADD CONSTRAINT FK_PORTLINK_SRC
  FOREIGN KEY (port_src) REFERENCES CYT_NETWORKPORTS(port_id);

ALTER TABLE CYT_PORT_LINKS ADD CONSTRAINT FK_PORTLINK_DST
  FOREIGN KEY (port_dst) REFERENCES CYT_NETWORKPORTS(port_id);

ALTER TABLE CYT_USERS ADD CONSTRAINT FK_USER_ENTITY
  FOREIGN KEY (entity_id) REFERENCES CYT_ENTITIES(entity_id);

ALTER TABLE CYT_USERS ADD CONSTRAINT FK_USER_PROFILE
  FOREIGN KEY (profile_id) REFERENCES CYT_PROFILES(profile_id);

ALTER TABLE CYT_USERS_DETAIL ADD CONSTRAINT FK_USERDET_USER
  FOREIGN KEY (user_id) REFERENCES CYT_USERS(user_id) ON DELETE CASCADE;

ALTER TABLE CYT_USERS_PROFILES ADD CONSTRAINT FK_UP_USER
  FOREIGN KEY (user_id) REFERENCES CYT_USERS(user_id) ON DELETE CASCADE;

ALTER TABLE CYT_USERS_PROFILES ADD CONSTRAINT FK_UP_PROFILE
  FOREIGN KEY (profile_id) REFERENCES CYT_PROFILES(profile_id);

ALTER TABLE CYT_USERS_PROFILES ADD CONSTRAINT FK_UP_ENTITY
  FOREIGN KEY (entity_id) REFERENCES CYT_ENTITIES(entity_id);

ALTER TABLE CYT_COMPUTERS ADD CONSTRAINT FK_COMP_ENTITY
  FOREIGN KEY (entity_id) REFERENCES CYT_ENTITIES(entity_id);

ALTER TABLE CYT_COMPUTERS ADD CONSTRAINT FK_COMP_LOCATION
  FOREIGN KEY (location_id) REFERENCES CYT_LOCATIONS(location_id);

ALTER TABLE CYT_COMPUTERS ADD CONSTRAINT FK_COMP_TYPE
  FOREIGN KEY (type_id) REFERENCES CYT_COMPUTER_TYPES(type_id);

ALTER TABLE CYT_COMPUTERS ADD CONSTRAINT FK_COMP_MODEL
  FOREIGN KEY (model_id) REFERENCES CYT_COMPUTER_MODELS(model_id);

ALTER TABLE CYT_COMPUTERS ADD CONSTRAINT FK_COMP_MANUFACTURER
  FOREIGN KEY (manufacturer_id) REFERENCES CYT_MANUFACTURERS(manufacturer_id);

ALTER TABLE CYT_COMPUTERS ADD CONSTRAINT FK_COMP_USER
  FOREIGN KEY (user_id) REFERENCES CYT_USERS(user_id);

ALTER TABLE CYT_COMPUTERS ADD CONSTRAINT FK_COMP_TECH
  FOREIGN KEY (tech_user_id) REFERENCES CYT_USERS(user_id);

ALTER TABLE CYT_COMPUTERS_DETAIL ADD CONSTRAINT FK_COMPDET_COMP
  FOREIGN KEY (computer_id) REFERENCES CYT_COMPUTERS(computer_id) ON DELETE CASCADE;

ALTER TABLE CYT_NETEQUIP ADD CONSTRAINT FK_NETEQ_ENTITY
  FOREIGN KEY (entity_id) REFERENCES CYT_ENTITIES(entity_id);

ALTER TABLE CYT_NETEQUIP ADD CONSTRAINT FK_NETEQ_LOCATION
  FOREIGN KEY (location_id) REFERENCES CYT_LOCATIONS(location_id);

ALTER TABLE CYT_NETEQUIP ADD CONSTRAINT FK_NETEQ_MANUFACTURER
  FOREIGN KEY (manufacturer_id) REFERENCES CYT_MANUFACTURERS(manufacturer_id);

ALTER TABLE CYT_IPADDRESSES ADD CONSTRAINT FK_IP_ENTITY
  FOREIGN KEY (entity_id) REFERENCES CYT_ENTITIES(entity_id);

ALTER TABLE CYT_INFOCOMS ADD CONSTRAINT FK_IC_ENTITY
  FOREIGN KEY (entity_id) REFERENCES CYT_ENTITIES(entity_id);

ALTER TABLE CYT_ASSET_TRANSFER ADD CONSTRAINT FK_TRANS_COMPUTER
  FOREIGN KEY (computer_id) REFERENCES CYT_COMPUTERS(computer_id);

ALTER TABLE CYT_ASSET_TRANSFER ADD CONSTRAINT FK_TRANS_SRC
  FOREIGN KEY (entity_src) REFERENCES CYT_ENTITIES(entity_id);

ALTER TABLE CYT_ASSET_TRANSFER ADD CONSTRAINT FK_TRANS_DST
  FOREIGN KEY (entity_dst) REFERENCES CYT_ENTITIES(entity_id);

ALTER TABLE CYT_ASSET_TRANSFER ADD CONSTRAINT FK_TRANS_USER
  FOREIGN KEY (initiated_by) REFERENCES CYT_USERS(user_id);

SELECT constraint_name, table_name, status
FROM   user_constraints WHERE constraint_type = 'R'
ORDER BY table_name;
