
CREATE DATABASE LINK DBLINK_PAU
  CONNECT TO APPLI_GLPI IDENTIFIED BY "AppGLPI_2026!"
  USING '(DESCRIPTION=
           (ADDRESS=(PROTOCOL=TCP)(HOST=oracle_pau)(PORT=1521))
           (CONNECT_DATA=(SERVICE_NAME=FREEPDB1)))';

CREATE DATABASE LINK DBLINK_PAU_RO
  CONNECT TO AUDITEUR_PAU IDENTIFIED BY "Audit_Pau_2026!"
  USING '(DESCRIPTION=
           (ADDRESS=(PROTOCOL=TCP)(HOST=oracle_pau)(PORT=1521))
           (CONNECT_DATA=(SERVICE_NAME=FREEPDB1)))';

-- Tests de validation
SELECT 'PING PAU OK' AS test, SYSDATE AS date_test FROM DUAL@DBLINK_PAU;
SELECT 'DBLINK_PAU OK'    AS test, COUNT(*) AS nb FROM CYT_COMPUTERS@DBLINK_PAU;
SELECT 'DBLINK_PAU_RO OK' AS test, COUNT(*) AS nb FROM CYT_USERS@DBLINK_PAU_RO;
